name: diet-assessment-api

services:
  api:
    container_name: ${API_CONT_NAME}
    image: diet-api_image
    restart: unless-stopped
    build:
      dockerfile: ./Dockerfile
    ports:
      - "${API_PORT}:8080"
    env_file:
      - .env
    depends_on: 
      db:
        condition: service_healthy
    networks:
      - net
      
  db:
    container_name: ${DB_CONT_NAME}
    image: postgres:17
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      retries: 5
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env
    volumes: 
      - vol:/var/lib/postgresql/data
    networks:
      - net

networks:
  net:
    name: diet-api_net

volumes:
  vol:
    name: diet-db_data